export const EMAIL_CODES_ERRORS = {
  INVALID_FORMAT: "INVALID_FORMAT",
  ALREADY_EXIST: "EMAIL_ALREADY_EXIST",
  NOT_VALID: "NOT_VALID",
};

export const PASSWORD_CODES_ERRORS = {
  WEAK_FORMAT: "WEAK_FORMAT",
  CONFIRMATION_FAILED: "CONFIRMATION_FAILED",
};

export const GENERAL_CODES_ERRORS = {
  MAX_LENGTH: "MAX_LENGTH",
  MIN_LENGTH: "MIN_LENGTH",
  ILLEGAL_CHARACTER: "ILLEGAL_CHARACTER",
  UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
};
